node {
        stage 'Initialize' {
        git url: 'https://github.com/jglick/simple-maven-project-with-tests.git'
        def mvnHome = tool 'M3'
        }
        
        stage 'Build' {
        sh "${mvnHome}/bin/mvn -B -Dmaven.test.failure.ignore verify"
        }
        
        stage 'Test' {
        step([$class: 'ArtifactArchiver', artifacts: '**/target/*.jar', fingerprint: true])
        step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
        }
        
        stage 'Deploy' {
        echo 'Project Deployed'
        }
        
        stage 'Cleanup' {
        echo 'Cleanup Done'
        }
}
